import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({
  subsets: ["latin"], // Loads only the Latin subset
  weight: ["400", "500", "600", "700"], // Load specific weights
  display: "swap",
});

export const metadata: Metadata = {
  title: "DuskDrop - Temporary File Sharing Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" />
      </head>
      <body className={`${inter.className}`}>
        <Header />
        <div className="bg-gradient-to-br from-gray-950 via-gray-900 to-gray-950 grid grid-rows-[1fr_auto]">
          <div className="max-w-6xl mx-auto">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
